version: '3.7'

services:
  pi-app:
    build:
      context: ./pi/app
    env_file:
      - env.pi-app
    depends_on:
      - api
    environment:
      MOCK_HARDWARE: 'true'
      API_ENDPOINT: http://api:3001
      API_TOKEN: pi_auth_token
      # PERIODIC_READING_INTERVAL: 5
    # command: ["python3", "-u", "./test.py"]

  api:
    build:
      context: ./api
    env_file:
      - env.api
    depends_on:
      - mongodb
      - mongo-express
    environment:
      PORT: 3001
      JWT_SECRET: jwt_secret
      MONGODB_DATABASE: iotdb
      MONGODB_AUTHENTICATION_DATABASE: admin
      MONGODB_USER: user
      MONGODB_PASSWORD: password
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      AUTH_TOKEN: pi_auth_token

    ports:
      - 3001:3001
    expose:
      - 3001

  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
